esphome:
  name: ESPHome-sofarg3
  friendly_name: ESPHome SofarG3


esp32:
  board: esp32-c3-devkitm-1
  #board: az-delivery-devkit-v4
  framework:
    type: arduino


# Enable logging
logger:
  baud_rate: 0 #the rs485 is wired to the hardware UART on the the c3

# Enable Home Assistant API
api:

ota:
 

wifi:
  ssid: !secret wifi_ssid #you put george in your secrets.yaml (you'll have it setup for the blue box anyway!)
  password: !secret wifi_password


uart:
  id: mod_bus
  #esp32-c3 has a set pinout
  tx_pin: 21
  rx_pin: 20
  #need to double check this, possibly its 9600 and 1 stop bit
  baud_rate: 9600
  stop_bits: 1
  parity: NONE
  

modbus:
  flow_control_pin: 5
  id: modbus1
  

modbus_controller:
  - id: ecoModbus
    ## the Modbus device addr set on inverter
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 15s
    command_throttle: 100ms

sensor: 
  - platform: modbus_controller
    modbus_controller_id: ecoModbus
    name: "PV1 Power",
    id: pv1Power
    register_type: holding
    address: 0x0586 #register is in hex, could also be addressed as an decimal 1414
    unit_of_measurement: "ºC"
    value_type: S_WORD #signed (could be unsigned, U_WORD)
    icon: "mdi:solar-power"
    filters:
      multiply: 10

  - platform: modbus_controller
    modbus_controller_id: ecoModbus
    name: "PV2 Power",
    id: pv2Power
    register_type: holding
    address: 0x0589 #register is in hex, could also be addressed as an decimal 1414
    unit_of_measurement: "ºC"
    value_type: S_WORD #signed (could be unsigned, U_WORD)
    icon: "mdi:solar-power"
    filters:
      multiply: 10

